# Generated by Django 4.1.6 on 2023-09-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('fecha_de_contratacion', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Empleadx',
                'verbose_name_plural': 'Empleadxs',
                'ordering': ['-fecha_de_contratacion'],
            },
        ),
    ]
