# Generated by Django 4.1.6 on 2023-09-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('es_propia', models.BooleanField(default=True)),
                ('patente', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('estado_mantenimiento', models.CharField(choices=[('Operativo', 'Operativo'), ('Mantenimiento', 'Mantenimiento'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Operativo', max_length=50)),
                ('fecha_vencimiento_seguro', models.DateField()),
            ],
        ),
    ]
