# Generated by Django 4.1.6 on 2023-07-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0002_alter_obra_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='name',
            new_name='title',
        ),
    ]
