# Generated by Django 4.1.6 on 2023-08-03 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Obras', '0004_alter_obra_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='image_1',
            field=models.ImageField(default='Null', upload_to='obras', verbose_name='Imagen1'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='image_2',
            field=models.ImageField(default='Null', upload_to='obras', verbose_name='Imagen2'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='image_3',
            field=models.ImageField(default='Null', upload_to='obras', verbose_name='Imagen3'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
