# Generated by Django 4.1.6 on 2023-09-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loteos', '0002_rename_title_lote_id_lote_alter_lote_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
