# Generated by Django 4.1.6 on 2023-09-04 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loteos', '0003_alter_lote_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='id',
        ),
        migrations.AlterField(
            model_name='lote',
            name='id_lote',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(limit_value=102)], verbose_name='Titulo'),
        ),
    ]
