# Generated by Django 4.1.6 on 2023-09-04 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loteos', '0004_remove_lote_id_alter_lote_id_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='id_lote',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(limit_value=102)], verbose_name='id_lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='image',
            field=models.ImageField(default='Null', upload_to='loteos', verbose_name='Imagen'),
        ),
    ]
