# Generated by Django 4.1.6 on 2023-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loteos', '0005_alter_lote_id_lote_alter_lote_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='price',
            field=models.IntegerField(default='Null', verbose_name='Precio'),
        ),
    ]
