# Generated by Django 4.1.6 on 2023-09-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loteos', '0006_lote_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
