# Generated by Django 4.1.6 on 2023-09-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loteos', '0007_alter_lote_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('Vendido', 'Vendido'), ('Disponible', 'Disponible')], default='Disponible', max_length=10, verbose_name='Estado'),
        ),
    ]
