# Generated by Django 4.1.6 on 2023-09-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loteos', '0007_alter_lote_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='price',
        ),
    ]
